baseURL = 'https://blog.karthikrp.com/'
languageCode = 'en-us'
title = 'Reflections'
theme = 'archie'
copyright = "© Karthik Ramaswamy Padmanabhan"

paginate=4 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "A Whole New Thought"

[[params.social]]
name = "X"
icon = "twitter"
url = "https://twitter.com/karthographer/"
favicon = "favicon.ico"  


[[params.social]]
name = "Facebook"
icon = "facebook"
url = "https://www.facebook.com/karthikrpad/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4